### ISSUE TITLE
syntax error at or near `POP_BLOCK`...

### ISSUE THREAD

**Issue by drunkwolfs** [rocky/python-uncompyle6#11]
python34 C:\Python34\Scripts\uncompyle6 --asm -o C:\dc\ 1_Lisa.pyc

```
...
...
        1510    LOAD_NAME         'resp'
        1513    CALL_FUNCTION     '1 positional, 0 keyword pair'
        1516    POP_TOP           ''
        1517    JUMP_FORWARD      'to 1520'
      1520_0    COME_FROM         '1517'
        1520    JUMP_BACK         1476
        1523    POP_BLOCK         ''
      1524_0    COME_FROM         '1456'
      1524_1    COME_FROM         '1459'
        1524    JUMP_BACK         1200
        1527    POP_BLOCK         ''
      1528_0    COME_FROM         '1197'
        1528    JUMP_BACK         1163
        1531    POP_BLOCK         ''
      1532_0    COME_FROM         '1160'
        1532    JUMP_FORWARD      'to 1535'
      1535_0    COME_FROM         '1532'
        1535    LOAD_CONST        ''
        1538    RETURN_VALUE      ''
decompiled 0 files: 0 okay, 1 failed
```

python34 C:\Python34\Scripts\uncompyle6 --asm 1_Lisa.pyc
```
...
...
        1524    JUMP_BACK         1200
        1527    POP_BLOCK         ''
      1528_0    COME_FROM         '1197'
        1528    JUMP_BACK         1163
        1531    POP_BLOCK         ''
      1532_0    COME_FROM         '1160'
        1532    JUMP_FORWARD      'to 1535'
      1535_0    COME_FROM         '1532'

Syntax error at or near `POP_BLOCK' token at offset 1527

# Can't uncompile C:\Python34\home\python-uncompyle6-master\bin\1_Lisa.pyc
```

pyc and decompiled files using pycdc https://drive.google.com/open?id=0B69FzC4j62F9ZmlILUt3eWlvSVE
pycdc decompiled larger number of files than uncompyle6.

**Comment by rocky** [comment]
Given the size and nature of this suite of programs it feels like you are asking people of good will to help you do something which is possibly unethical. Assure me this is not the case by explaining what's going on here.

(If this is unethical, that you are also asking for this work is for free just a smaller consideration of rudeness.)

Who wrote this program? And how is it that such a large optimized Python program has its source code lost? 

As for the specifics of the bug, I note that pycdc gives a Segment Violation when working on this. I'm guessing on both cases it is because the code has been optimized.

To find the bug in uncompyle6, you or someone would need to get the source code and whittle it down to the smallest source code that exhibits the problem. Or from the source code byte compile it without optimization to another version of Python that produces alternative equivalent bytecode. If that works in uncompyle6, we can compare functionally equivalent bytecode.

**Comment by drunkwolfs** [comment]
>Who wrote this program?

Someone else. Author unknown.
>Python program which makes calls to http://rucaptcha.com has its source code lost?

This program is a chat bot for social network VKontakte.
I'm interested to see some of the functions of this program.

http://rucaptcha.som - used to bypass the captcha in the social network VKontakte.

**Comment by rocky** [comment]
> I'm interested to see some of the functions of this program.

Looks like a good chunk of that got translated. If you are able to get the source code to this Python program or another program can turn this into Python, then there's hope of getting this fixed here. So Ill close this. If things change then feel free to reopen. 

uncompyle6 and all of the other uncompyle programs have tons of programs, especially optimized Python, that can't be parsed to source code.
