### ISSUE TITLE
Syntax error ???

### ISSUE THREAD

**Issue by derfox** [rocky/python-uncompyle6#146]
File "c:\program files\python36\lib\site-packages\uncompyle6\semantics\pysource.py", line 2521
    except python_parser.ParserError, e: 

SyntaxError: invalid syntax

**Comment by rocky** [comment]
Most likely you are using the Python 2.4 code on 2.7+. Compare with https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/pysource.py#L2521

How did you get the code you are running?

**Comment by derfox** [comment]
I am using Python 3.6.4, and I installed uncompyle6 using pip install. 
And yes, the line looks different in the link you gave me. I will have to check it when I get back home this evening.

**Comment by derfox** [comment]
All good now, I have installed it from github.

**Comment by rocky** [comment]
Ok. I think I've found where I made my mistakes and have fixed those. I follow a somewhat automated release process, but I must have messed up somehow. And pypi and its packaging are not all that good about allowing two branches of source code to cover a single package. 

Since this has happened before, I just added an additional check at setup.py time to make sure we have the right branch. 

In sum, thanks for reporting.
