### ISSUE TITLE
Doesn't work when installed with pip

### ISSUE THREAD

**Issue by equal-l2** [rocky/python-uncompyle6#147]
I've installed uncompyle6 via:

```
$ pip3 install uncompyle6
```

When I run uncompyle6 or pydisassemble, they don't work and show the error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pydisassemble", line 7, in <module>
    from uncompyle6.bin.pydisassemble import main
  File "/usr/local/lib/python3.6/site-packages/uncompyle6/__init__.py", line 48, in <module>
    import uncompyle6.semantics.pysource
  File "/usr/local/lib/python3.6/site-packages/uncompyle6/semantics/pysource.py", line 2521
    except python_parser.ParserError, e:
                                    ^
SyntaxError: invalid syntax
```

**Comment by rocky** [comment]
Thanks for reporting. I just checked and it looks _like all of the eggs were build from the wrong source_

In issue #146 the tarball was also build trom the wrong source (these are all from the python 2.4 branch).

I have just removed all eggs from pypi. If you can use wheel then do that. Or install from git. 

I will be putting out another release soon which I hope will fix all of this (and add the latest bug fixes). 

Sorry for the hassle. I make mistakes which is why I work on debuggers (and even got interested in this project in the first place).

**Comment by equal-l2** [comment]
Unfortunately, wheel doesn't work either.
They seems to be built from "the wrong source", too.

**Comment by equal-l2** [comment]
It works perfectly now!
Thank you for the fix.
