### ISSUE TITLE
Functions decompilation should have better API

### ISSUE THREAD

**Issue by KOLANICH** [rocky/python-uncompyle6#159]
For now it is not very easy to decompile functions with it I guess it should be as easy as
```uncompyle(func, emitAST=False)``` to get the source (including signature) as a string and ```uncompyle(func, emitAST=True)``` to get the source as AST

**Comment by rocky** [comment]
Actually, it is pretty easy: here's a complete program to do it:

```
import sys
from uncompyle6 import deparse_code
def deparse_test(co):
    sys_version = float(sys.version[0:3])
    return deparse_code(sys_version, co).text

print(deparse_test(deparse_test.__code__))
```

Yeah the most complicated thing is getting the version, so in commit 859ce22 we now  allow version=None and you can use `return deparse_code(None, co).text` instead.

**Comment by KOLANICH** [comment]
I know that it is easy, but
1 IMHO this should go out of the box
2 it doesn't generate full function definition, only its body.

so IMHO the API could be better.

**Comment by rocky** [comment]
This issue seems to meander around. 

> so IMHO the API could be better.

Yep, it could be. If you want to submit a merge request to improve it by all means do so. 

It was also a mistake to have version be a required parameter by putting it first. To address that it would be an incompatible API change and would require changing the major number and all of the packages that use the current API. 

But that's the way it is. If you
