### ISSUE TITLE
Decompilation of optimized "if False:" leaving dead code

### ISSUE THREAD

**Issue by njwhite** [rocky/python-uncompyle6#17]
```
uncompyle6.semantics.pysource.deparse_code(3.5, (lambda: 2 if False else 3).func_code)
````
...gives...
```
if False:
    return 2
```
i.e. the else branch is missing? This fails for all the code versions I've tried (e.g. 2.7)

**Comment by rocky** [comment]
I am not sure there is hope in being able to address this specific problem.

First though I should note that the code you have looks fishy:  `func_code` works on Python 2.x not Python 3.x so what you are asking is to use the rules for Python 3.5 decoding on code compiled dynamically for Python 2.x. (I never thought I'd find a use for Python's massive cross version API irregularities.) 

That said, sure, if you try to deparse this not just on uncmpyle6, but any other unparser out there, it probably won't work. 

Let me explain what's going on. To make it easy for everyone I've compiled the Python program for various versions of Python and put that in https://gist.github.com/rocky/4b21002dc0df51970ce12289629a085a 

It looks like later Python 3 versions optimize the "if True" away; this leaves the cryptic bytecode: 
```
                0       LOAD_CONST              2: 2
                3       RETURN_VALUE            
                4       LOAD_CONST              3: 3
                7       RETURN_VALUE            
```
which is kind of weird. Not removing the unreachable code at offset 4 will bolix decompilation. Without that, it will show the code as 

```python
   lambda: 2
```

which is a fair decompilation. 

When I run it on the current uncompyle6 in github, bytecode from 2.7 and 3.3 work while 3.4 and 3.5 don't. So in 3.4 that optimization must have been added.

In contast, pycdc fails on _all_ of these. pycdc gives two different wrong deparses. 

But from the standpoint of uncompyle6 the only thing I can think of is looking for such unreachable code and removing it in 3.4 and beyond. I'm not sure I'd try that in those versions of Python where things work, because if it ain't broke, don't fix it. And uncompyle6 is not trying to be a code optimizer.

**Comment by njwhite** [comment]
@rocky thanks for the investigation - but I think optimisation is a red herring. This:
```
def fn(self):
    if self.id == 'hat':
        return 4
    return 3
```
...also mis-decompiles:
```
import uncompyle6
uncompyle6.semantics.pysource.deparse_code(2.7, fn.func_code)
```
as:
```
if self.id == 'hat':
    return 4
```

**Comment by rocky** [comment]
This particular bug is on me, and commit 79f4893 may address this problem. The problem has nothing to do with if statements, it has to do with final return statements with a constant. 

This stuff is very slippery. Your original bug report attributed the problem to ternary if. Then you assumed it might have something to do with "if" of some sort. There is in fact two bugs in both examples and they are different bugs. And neither had anything to do with "if" statements ternary or not. 

Ironically fact the bug where we remove a final return statement assists in cases where that code is dead as it sometimes was in the first program. 

So as you've done, do report real programs and facts. Also be aware that putting a number not the same as from sys.version is not advisable in: 

```
uncompyle6.semantics.pysource.deparse_code(2.7, fn.func_code)
``` 

If you want to have more confidence in the accuracy of your guesses as to what's wrong start using the "showgrammar" and "showast" options of parse_code().

**Comment by rocky** [comment]
Think this was fixed. If not, reopen.
