### ISSUE TITLE
decompile function code into readable script

### ISSUE THREAD

**Issue by jimy-byerley** [rocky/python-uncompyle6#179]
Hi Rocky,
I don't really know if this is an issue or a question about usage of the library since I didn't found a lot of documentation about this project.
I'm trying to decompile a single function, not a module at all. So I found function `uncompyle6.main.decompile` to do it. When I execute it this way, I get the following error:
```

>>> uncomp.main.decompile(3.5, f.__code__) 
# uncompyle6 version 3.2.3
# Python bytecode 3.5
# Decompiled from: Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
# [GCC 6.3.0 20170118]
# Embedded file name: <stdin>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6/main.py", line 109, in decompile
    is_pypy=is_pypy)
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6/semantics/pysource.py", line 2266, in code_deparse
    deparsed.gen_source(deparsed.ast, co.co_name, customize)
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6/semantics/pysource.py", line 2110, in gen_source
    self.println(self.text)
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6/semantics/pysource.py", line 398, in println
    self.write(*data)
  File "/usr/local/lib/python3.5/dist-packages/uncompyle6/semantics/pysource.py", line 394, in write
    self.f.write(out)
AttributeError: 'NoneType' object has no attribute 'write'

```
Isn't that the good way to run this function ?
I read code of functions noticed in the traceback, but I didn't found any sort of declaration of `self.f` that is asked at the Exception point.

P.S.:  my goal is to use uncompyle6 to print python functions to terminal or into files. I'm starting a project in which some functions will automatically generate python code objects I need to look into.
         congrats for having maintained this impressive module by yourself all this time. It's ... so huge !

**Comment by rocky** [comment]
The error message above is saying that you need to pass a parameter that can has a "write" attribute that the decompile function can use to write its results to.

But the top-level function to use to deparse a function is [`code_deparse`](https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/__init__.py#L60). An example showing its use is   the test [pytest/test_single_compile](https://github.com/rocky/python-uncompyle6/blob/master/pytest/test_single_compile.py) but in your case if you are compiling a whole function you don't need the 'single' paramenter since that is for single statements rather than functions. 

As for the documentation, if you find something lacking feel free to improve it. Adding a wiki entry is something with a low-tech barrier to entry. Or suggest (and better work on) something else. 

Yes, the project is big, but there is at least one big refactor that's needed to improve accuracy, and there are a still  number of gaps in the code. So help is always needed.
