### ISSUE TITLE
Please begin testing against python-3.7

### ISSUE THREAD

**Issue by dol-sen** [rocky/python-uncompyle6#184]
Includes your other related applications...  
(no need to spam them all) python-xdis, python-spark...

**Comment by rocky** [comment]
Seems to be too new for Travis CI See https://travis-ci.org/rocky/python-uncompyle6/jobs/403582549

**Comment by dol-sen** [comment]
ah, seems tox beat travis to it...
https://github.com/tornadoweb/tornado/commit/8952120d54ebabf7add64565d1a1c4546298bbe8

no worries then.

**Comment by rocky** [comment]
>  seems tox beat travis to it...
You mean appveyor. 

This project may be going on hold for a little but unless others get involved. So I'll say that i know that in general 3.7 support is lacking and it will probably stay that way unless others pitch in or it turns out I need it for my own personal use.

I'm going to close this. I'll leave it to you then to reopen when Travis works.
