### ISSUE TITLE
Use of uncompyle6 as an AST?

### ISSUE THREAD

**Issue by jpivarski** [rocky/python-uncompyle6#220]
(Not a bug report or a feature request, but a question.)

I'd like to use uncompyle6 to turn user-written lambdas into ASTs. They don't have to be exactly Python's `ast.AST` subclasses (as requested in #29), but a math-focused expression tree that I can manipulate in a (largely?) Python version-independent way.

Maybe I'm supposed to subclass `uncompyle6.semantics.pysource.SourceWalker` and override all the methods that start with `n_`, replacing everything that produces text? Are there any other examples of `SourceWalker` subclasses that produce data structures, rather than text? Would I need to worry about Python version dependence, or has that been normalized upstream of the `SourceWalker`?

**Comment by rocky** [comment]
I'd like to understand more, more details so I can talk more intelligently about this. But to try to speed things up let me just start talking (and hope this moves the discussion forward). 

So yes, at first sight, it might seem natural that since there is this file called `semantics/fragments.py` which subclasses `SourceWalker,  let's simply do the same thing. 

But here is I think a better approach. Write another pass which starts with the SourceWalker tree, or a FragmemtsWalker tree (if you just want to focus on something smaller than a function) then transform that. As you have noted, these things right now have to worry about changes in the underlying bytecode. And they worry about that a lot. 

However in the resulting tree a lot of the changes due to bytecode generation difference have been abstracted away. There still are Python version differences, but those are more fundamental, like the fact that before 3.5 or so there weren't format strings. Or 'old style" Python classes versus the new ones. Changes in nodes as a result of function annotations, and so on

But also, I should point out that this is also not all that altruistic (although right now I think it the cleaner thing to do). I have long been meaning to add such another layer to reorganiize the tree to do things like turn:

```
if x: 
    raise AssertionError
```

into 

```
assert not x
```

Some things like this are already done interspersed in the existing code, so once a clean pass is made, a lot of these code can be pulled out.

**Comment by jpivarski** [comment]
Thanks for the feedback!

In the last day or so, I've been working on this and found a solution that I'm happy with. I was about to follow up on this thread, but you beat me to it.

This is my (growing) implementation): https://github.com/diana-hep/rejig/blob/master/rejig/pybytecode.py

I started by filling a Walker class with a `n_` method for every token and non-terminal symbol used by any version of Python (https://github.com/diana-hep/rejig/blob/master/generate/pybytecode.py). Then I decided that, for my purposes, the Walker should be neither `preorder` nor `postorder` but recursive: I'm not serializing the tree, I'm turning it into another tree. So my Walker doesn't even inherit from `GenericASTTraversal`.

Without the constructor and methods of a `SourceWalker`, it doesn't make sense to try to use it in `uncompyle6.code_deparse`, so I just figured out how that calls the bytecode parser (`uncompyle6.parser.get_python_parser` and then `uncompyle6.parser.parse`) and I'm calling the parser directly.

So I'm looking at bytecode instructions and non-terminal symbols, and I expect to have to do a little Python version handling. Nevertheless, there's still a huge "value added" due to the fact that you've parsed the bytecode into a tree: figuring out where to start and stop in a stream of bytecodes would be a lot of work! (Which I thank you for!)

My problem is a little easier in that I'm only interested in Python 2.7 and above, and I'm only interested in expressions, assignments, and (non-recursive) function definitions—I'm using this to pick out a declarative Python subset for vectorized calculations. (A little broader in scope than NumExpr, hiding the distinction between fused calculations in a loop and array-at-a-time calculations like Numpy. The decompilation is so that expressions don't have to be written inside of strings—they can be syntax-colored like everything else.)

Thanks for this great project!
