### ISSUE TITLE
For loop with embedded for loop is not decompiled correctly

### ISSUE THREAD

**Issue by dontech** [rocky/python-uncompyle6#225]
Hi uncompile6/rocky.

Thanks for your excellent tool! We love it!

## Description

The following simple piece of code cannot decompile properly.
The code is running on Python 2.7

`from test.test.test import m`
`for f in (f for f in dir(m) if f.startswith('hello')):`
`    ms[f] = m`

When compiled and decompiled, it turns into:

`from test.test.test import m`
`for f in (f.startswith('hello') and f for f in dir(m)):`
`    ms[f] = m`

## How to Reproduce

Compile, and decompile.

## Expected behavior

Correctly decompile the code. Using the decompiler from https://sourceforge.net/projects/easypythondecompiler/, the code becomes decompiled correctly

## Environment

Decompiled from: Python 2.7.16 (default, Mar 20 2019, 12:15:19)

Thanks,

/pedro

**Comment by dontech** [comment]
> Really? Then why haven't you upvoted/starred the project? (Actually it looks like you are very stingy about doing this in general).

Ah, sorry about that. :-)

>Are you up for taking a shot at trying to fix? Basically using the -t option on uncompyle6 or uncompyle2 you'll see the tree derived from the code.

OK. If time permits it we might take a crack at it. Thanks for your time.

/pedro

**Comment by rocky** [comment]
Although I fixed this, there is a lot of other work I need to get to. So look at b57ca39 which is pretty short - a couple of lines added to one source-code file. 

The bulk of the change was updating a runnable test. But adding such runnable tests I think is important to try to improve decompilation quality. (It's something that I just don't see in the other decompilers that much, although it was a focus back in the early Python 1.5-2.3 days of this project). 

Since there is a lot of other work I need to get to, the other bug reports will probably wait a bit. So study this one to see how it works and if the others might be fixed in a similar way.

**Comment by dontech** [comment]
Hi,

Thanks for fixing this. I know some people who will be happy.

> The bulk of the change was updating a runnable test.

Yes. Automatic testing is always the way to go.

Thanks,

/pedro
