### ISSUE TITLE
Unknown Magic Number 3394

### ISSUE THREAD

**Issue by bkennard18** [rocky/python-uncompyle6#303]
Im getting this Unknown Magic Number error when i try to run uncompyle6, clearly. The magic number is indeed in the magics.py file as well. I was getting an Unknown Magic Number 227 error before, and i changed the hex headers and now im getting this error for a number that shouldnt be unknown, as its tied with Python3.7.0. how do i avoid this?

**Comment by rocky** [comment]
What is it that leads you to believe 227 is a valid magic number?

**Comment by bkennard18** [comment]
The only time 227 has come up was when i was trying to decompile and the error was raised. After searching for an answer i just tried to change the headers. If you have advice on what i should do about either 227 or 3394 then id be happy to hear it. Ive tried everything that i could think of and still no leeway. Thanks!

**Comment by rocky** [comment]
Sorry, this isn't working out. I am not sure what you are doing, but I don't time to try to figure it out  and you don't seem to be able describe it. 

Maybe someone on one of the general help forums might be able to guide you through the steps to elicide clearly what you are doing and how to do it. 

One thing that's clear right now is that this isn't an uncompyle6 but. But if it turns out it is feel free to come back. And when you do follow the template that's given in the issue when you open it.
