### ISSUE TITLE
Python2.7: code block merged into `else` incorrectly

### ISSUE THREAD

**Issue by foldl** [rocky/python-uncompyle6#314]
## Description

A module when compiled by Python 2.7: code block after `else` is merged into `else` incorrectly.

## How to Reproduce

Compile below module `bug.py` using Python 2.7:

```console
$ python -m py_compile bug.py
```

```python
# -*- coding: utf-8 -*-
def foo():
    if a <= x:
        if a.a > 0:
            b = c
        else:
            if a.e > 0:
                b = f
        print("bug here")
        if b < f:
            return 1
```

Then decompile it:

```console
$ uncompyle6 bug.pyc
```

## Expected behavior

In decompiled result, `print("bug here")` should be in the top `if` block, but not the `else` block:

```python
# uncompyle6 version 3.6.6
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
# Embedded file name: bug.py
# Compiled at: 2020-05-12 11:02:05

def foo():
    if a <= x:
        if a.a > 0:
            b = c
        else:
            if a.e > 0:
                b = f
            print 'bug here'
            if b < f:
                return 1
# okay decompiling bug.pyc
```

## Environment

- Uncompyle6 version: uncompyle6 3.6.6
- Python version for the version of Python the byte-compiled the file: 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:26:54) [MSC v.1500 64 bit (AMD64)].
- OS and Version: Windows 10

**Comment by rocky** [comment]
Thanks for the bug report. It might be a while before I get around to looking into this.

If you are interested in working up a fix, the way I've been doing that now is by adding reduction rule checks on the control structures, and here I guess that would be in https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/parsers/reducecheck/ifelsestmt.py

The decompyle3 project has more of these since things have gotten more complex in the most recent Python versions, so there might be some check code from https://github.com/rocky/python-decompile3/blob/master/decompyle3/parsers/reducecheck/ifelsestmt.py that could be used.

**Comment by foldl** [comment]
Thanks for your in detail response. I have temporarily enabled the `ifelsestmt`reduce check, and it works like a charm.

**Comment by rocky** [comment]
> Thanks for your in detail response. I have temporarily enabled the ifelsestmtreduce check, and it works like a charm.

You mean _dis_-abled, right?

**Comment by foldl** [comment]
I un-commented below one in parser27.py:

```python
        # FIXME: Put more in this table
        self.reduce_check_table = {
            # "ifelsestmt": ifelsestmt,
            "or": or_check,
            "tryelsestmt": tryelsestmt,
            "tryelsestmtl": tryelsestmt,
        }
```

**Comment by rocky** [comment]
@foldl Sorry for the delayed reply. Yes, you are correct there should be an "ifelsestmt" check there.  Should be added in commit cc4ea47d
