### ISSUE TITLE
Decompilation failed

### ISSUE THREAD

**Issue by ShadowHunterRUS** [rocky/python-uncompyle6#38]
Python 2.7
uncompyle6 v 2.7.0
> Syntax error at or near `JUMP_BACK' token at offset 33

Source code:
```
for a in b:
	try:c()
	except:continue
```

**Comment by rocky** [comment]
Should be fixed by a5f45f2 . I greatly appreciate your strippinng the program down. Probably you should check this against larger thing you probably ran into because the heuristic used is a bit custom.

Looks like pycdc also has problems with this type of thing too.
- - - 

In case you are wondering what's up.... 

Jump optimization starting in Python 2.7 makes it difficult to distinguish constructs like _continue_ from the normal branching that is done at the end of that loop.  And actually, that _continue_ is a little superfluous. I suppose _pass_ would have been about the same thing.

As a heuristic, uncompyle6 does take into account things like whether the jump instruction starts on a new line or not.  But in your example, the continue is on the same line so that heuristic doesn't work and another was added. 

If you want to make things easy on uncompyle6, put "continue" statements on a new line.
