### ISSUE TITLE
When will you support decompile of 3.10?

### ISSUE THREAD

**Issue by nisanb** [rocky/python-uncompyle6#384]

**Comment by rocky** [comment]
The short answer is: I don't know. It depends.  And you can both influence things both in a positive and a negative way. (See below). 

This question has been asked a bit see #331, #353, #375, https://github.com/rocky/python-decompile3/issues/45 and probably others.

What has been pretty common and consistent here is that aside from the pleas (or please?) nothing really has been offered by those who have asked. By the way "offers" includes doing some of the work yourself. I've written a great deal about how the code works [here](https://github.com/rocky/python-uncompyle6/wiki/How-does-this-code-work%3F). 

There were a couple people who I imagine felt really good about themselves because they told everyone they sponsored the project privately. Presumably to such a large degree because that they both seemed to expect results soon.

However neither did. Maybe each _thought_  or _intended_ to do so and there was a glitch along the way. I have no idea because in both cases, other than public announcement, there wasn't any other evidence that anything had been done.  I certainly known know either's name. As happens on the internet people disappears as quickly as they appear.

But having said this, I'll also say that I have looked into 3.10 bytecode and decompilation and I think it is doable with the cleanups and changes I have been working on, largely privately. I do this kind of thing sometimes instead of a crossword puzzle or a cryptogram.  There is a lot of work to do, and, right now, I've been doing this, as I said, as I please. I probably will do 3.9 first since the gap there is a little smaller.

On the other hand , the

* laziness, apathy or lack of involvement (no evidence that you even looked at what was written already communicated) 
* whininess (when are you going to .. ? rather than what am I willing to do..?), and 
*  the general notion that people seem to use decompilation as a way get around an intentional barrier,

isn't a motivator for me to rush to make in-progress experiments public.

And I doubt that what I've done would be of use to those who want to get around the barrier either. So it is just as well.

**Comment by Gabriel-Sama34** [comment]
Ok finally I understand your thought you are a very wise person who has all my admiration.
