### ISSUE TITLE
Need help with decompilation

### ISSUE THREAD

**Issue by Hollikill** [rocky/python-uncompyle6#385]
Hello, I am new to using uncompyle6. I have a source file in this [zip folder](https://drive.google.com/open?id=19aG2jgCs5lZupx4diXSc4smMbYiRfJFM) (the .pyc extension file). When I try to decompile it, it seems to work correctly up until it hits some sort of error, possibly file corruption. I would appreciate help with any of the following:

- getting a .py file with the part that seems to decompile correctly
- getting a full .py file
- an explanation of how to fix this on my own

Full output in next post.

**Comment by Hollikill** [comment]
output file:
[https://drive.google.com/file/d/1QaLUsANHiwg9f2rJzQHha5aCn8wTSoJQ/view?usp=sharing](https://drive.google.com/file/d/1QaLUsANHiwg9f2rJzQHha5aCn8wTSoJQ/view?usp=sharing)

**Comment by rocky** [comment]
> Hello,

Hello, 

>  I am new to using uncompyle6.

Although a lot of people seem to have used it. It is used a lot also by people like yourself. 

I have a source file in this [zip folder](https://drive.google.com/open?id=19aG2jgCs5lZupx4diXSc4smMbYiRfJFM) (the .pyc extension file). When I try to decompile it, it seems to work correctly up until it hits some sort of error, possibly file corruption. I would appreciate help with any of the following:
> 
> * getting a .py file with the part that seems to decompile correctly
> * getting a full .py file
> * an explanation of how to fix this on my own

I looked at this briefly and it looks like a bug in uncompyle6. I imagine anyone who has any facility with Python would be able to set figure out how to work around this. 

Since this is open source code any of the millions of python programmers, or yourself, could fix. 

In reality, if you look at all the tags with "Volunteer wanted to help user"  or "volunteer" wanted you'll see amount of participation of people other than myself helping anyone else out is within the rounding error of 0. 

I could be wrong about someone else helping you out (and I hope I am), but if this is not the case, then you are basically asking me to do something and/or teach you to do something you can't do yourself. 

Where I come from, this is what you pay people for. This is not about "free software",  league of programmers etc. It's about you have a problem that you want someone else to take interest in to help you out. 

(yes, there is a bug in the program - I think - but there are lots of bugs in there)

Given this, if you sponsor the project, I'll take a look at it over some weekend to the level that I think warrants the sponsorship.

**Comment by rocky** [comment]
Looks like no one is available to help you. :-(
