### ISSUE TITLE
Wrong string printing in Python 2.7.18

### ISSUE THREAD

**Issue by andrem-eberle** [rocky/python-uncompyle6#444]
## Description

Strings are being decoded when printed on decompiled Python 2.7 code, see example below. The decompiler is eager to decode the chars, but Python2.7 issues an encoding error when trying to execute the decompiled version.

I was looking into xdis and, since the compiler puts the actual original string bytes in the pyc, I suppose it should be carried on without attempting at decoding for Python2.7 files? I could look into this if that is an acceptable solution.

## How to Reproduce

Input file:
```
a = '\xc3\xa5'
print(a)
```
python2.7 compileall & uncompyle6

## Output Given

```
a = 'å'
print a
```
If ran with Python 2.7, the above output will give encoding errors.

## Expected behavior

Better behavior would be to print the original string

## Environment

Python 2.7.18 for compileall
Python 3.8.16 for uncompyle6
Ubuntu 16.x

**Comment by andrem-eberle** [comment]
I have been trying some changes in how n_actions.py outputs the string. It is a bit contrived, but python string manipulation is a bit lacking, something like this:
```
if isinstance(data,str):
      res = data.encode('utf-8')
      res = repr(str(res)[2:-1]).encode('utf-8').decode('unicode_escape')
      self.write(res)
```
It changes the unicode to a unescaped version of bytes/ascii mixed string python likes.

Would this be acceptable?

**Comment by rocky** [comment]
> I have been trying some changes in how n_actions.py outputs the string. It is a bit contrived, but python string manipulation is a bit lacking, something like this:
> 
> ```
> if isinstance(data,str):
>       res = data.encode('utf-8')
>       res = repr(str(res)[2:-1]).encode('utf-8').decode('unicode_escape')
>       self.write(res)
> ```
> 
> It changes the unicode to a unescaped version of bytes/ascii mixed string python likes.
> 
> Would this be acceptable?

I would need more details. As with the other issues, I have a gut feeling that we need to mark types better inside the tokens of uncompyle6 and that might be made easier by marking the types in the instruction format of xdis.

So you don't spend a lot of time on something that may be going down something that might not be successful, I'd suggest creating a new branch in your fork, and making some changes there. 

 The change do not have to be perfect since the goal there would be to convey more details of a proposed solution.

**Comment by andrem-eberle** [comment]
I see your point, more clarity coming from the disasm would help, I agree. But the main issue here I believe is the attempt at decoding the byte array from the object file into utf-8, when the compiler doesn't really care about how printable the string is, it is simply moving the bytes around.

I was looking into another issue (which I haven't reported yet but it is very related to this one), where a string has non printable characters, like this:

```
st = u'\udef0'
```

That is a non-valid unicode char, and will throw a UnicodeDecodeError if you attempt to decode/print. I know that xdis just catches the exception and does something else, but I feel it shouldn't been trying to decode at all. Currently uncompyle6 outputs an utf-8 approximation, but it is incorrect. I suppose xdis could just provide the same string as issued in the .py file, something that could be achieved with an utf-8 to utf-16 converter. What do you think? I will open a branch and include all my ideas, then you can have a better look.

**Comment by rocky** [comment]
> I see your point, more clarity coming from the disasm would help, I agree. But the main issue here I believe is the attempt at decoding the byte array from the object file into utf-8, when the compiler doesn't really care about how printable the string is, it is simply moving the bytes around.

Which program when you say "compiler" are you talking about? "uncompyle6" or "xdis" (which is not a compiler). 
If "uncompyle6", then exactly _where_ is it doing this? 

> 
> I was looking into another issue (which I haven't reported yet but it is very related to this one), where a string has non printable characters, like this:
> 
> ```
> st = u'\udef0'
> ```
> 
> That is a non-valid unicode char, and will throw a UnicodeDecodeError if you attempt to decode/print. I know that xdis just catches the exception and does something else, but I feel it shouldn't been trying to decode at all. 

There is a bit of code in `xdis` that I now realize is flawed and should be handled by creating a special type for the kinds of objects that exist in one set of versions of Python (e.g. Python 2) that do not exist  in another set of Python versions (e.g. Python3). 

> Currently uncompyle6 outputs an utf-8 approximation, but it is incorrect. I suppose xdis could just provide the same string as issued in the .py file, 

We should reduce the guessing as to whether a string of bytes is valid ASCII, utf-8, or utf-16, and xdis should be doing the work for this. 

We will have to live with the fact that the original code may have been written in some less human-oriented string and we helpfully converted it to a more human-string.  Basically, there is no way we can detect which kind of string was originally given.  And since we have to pick one form all of the time, my preference is to pick the human-oriented string (when that is available) over the machine-oriented form.

**Comment by andrem-eberle** [comment]
> Which program when you say "compiler" are you talking about? "uncompyle6" or "xdis" (which is not a compiler). If "uncompyle6", then exactly _where_ is it doing this?

I meant the python compiler, the one generating the bytecode.

> We should reduce the guessing as to whether a string of bytes is valid ASCII, utf-8, or utf-16, and xdis should be doing the work for this.

Well yes, that is my idea. It seems all 'u' strings in python2 are utf-8, but that wasn't my point. What I meant is that python `decode('utf-8')` function try to turn utf-8 bytes into printable characters, while I think it would be better to convert non-ascii chars back to their '\uxxxx' and '\Uxxxxxxxx' form in the decompiled string for better compatibility.

> We will have to live with the fact that the original code may have been written in some less human-oriented string and we helpfully converted it to a more human-string. Basically, there is no way we can detect which kind of string was originally given. And since we have to pick one form all of the time, my preference is to pick the human-oriented string (when that is available) over the machine-oriented form.

I agree.
