### ISSUE TITLE
Option to not write file header

### ISSUE THREAD

**Issue by Nothing4You** [rocky/python-uncompyle6#87]
Hello,

please add a method that doesn't [force adding headers about uncompyle6 version etc](https://github.com/rocky/python-uncompyle6/blob/ed6cb9af79dfacab2c8a48291e68eb175d68a60e/uncompyle6/main.py#L27-L32).

**Comment by rocky** [comment]
Hello, 

Seems easy enough to do. Wondering what the motivation for this is though?

**Comment by Nothing4You** [comment]
Keeping possible extra noise out of diffs. I have a setup for automatically decompiling a larger project and putting it in a git repo to make it easy to analyze changes. I've been using wibitis uncompyle2 so far, and I'm trying if I can get it replaced by this if the performance is acceptable so I can get rid of the py2 dependency and run the process in py3 exclusively.

While doing some testing and comparing the outputs I have also found that this project adds quite a few redundant return statements, is that intended behavior? (e.g. last statement in a method being just "return")

**Comment by rocky** [comment]
Ok. Thanks for the information. Right now performance if anything has gotten worse on 2.7 since we are more focused on accuracy and handling Python bytecode other than 2.7. 

So if all you care about is decompiling 2.7, then I'd stick with wibiti's uncompyle6. (There have been a couple of bugs found in that like escaping triple-quoted strings, and handling complex number constants, some control flow and function prototypes, and handling if == precidence; but all of these tend to be arcane situations. Someone could probably take the code in uncompyle6 and back port it to wibiti uncompyle2.) 

> While doing some testing and comparing the outputs I have also found that this project adds quite a few redundant return statements, is that intended behavior?

While it isn't intended, it isn't unintended either. The code works simply by following grammar patterns it detects in the code. Possibly it is matching more return statements than the grammar used previously. 

In both, there's a special case hack to check to see if the last statement is a return statement https://github.com/rocky/python-uncompyle6/blob/master/uncompyle6/semantics/pysource.py#L1959-L1963

This test is probably used to come out True and no longer does. If this is important to fix, find a _small_ test case that exhibits the problem and file an issue for that. 

Oh, and if you fill a pull request for an option to disable outputting headers, this will probably get done sooner.

**Comment by rocky** [comment]
Closed because of lack of interest. In fact, it might not be a bad idea to go the other way. Maybe I should add my name in the meta comments.

**Comment by Nothing4You** [comment]
Why don't you just leave it open as a feature request? You don't have to implement it but you can keep it tracked.

**Comment by rocky** [comment]
Nah - Nothing4You ;-)
